# Generated by Django 5.1.6 on 2025-03-11 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='pecas',
            new_name='peca',
        ),
    ]
